/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.Date;
import javax.print.attribute.SetOfIntegerSyntax;


/**
 *
 * @author rumia
 */
public class IssueBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
    }
    
    public void getBookDetails(){
     int bookId= Integer.parseInt(txt_bookId.getText());
        try {
            Connection con =DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from book_details where book_id =?");
            pst.setInt(1,bookId);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
            lbl_bookId.setText(rs.getString("book_id"));
            lbl_bookName.setText(rs.getString("book_name"));
            lbl_author.setText(rs.getString("author"));
            lbl_quantity.setText(rs.getString("quantity"));
            
            
            }
        } catch (Exception e) {
        }
    
    }
    
    public void getStudentDetails(){
     int studentId= Integer.parseInt(txt_studentId.getText());
        try {
            Connection con =DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("select * from student_details where student_id =?");
            pst.setInt(1,studentId);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()){
            lbl_studentId.setText(rs.getString("student_id"));
            lbl_studentName.setText(rs.getString("name"));
            lbl_course.setText(rs.getString("course"));
            lbl_branch.setText(rs.getString("branch"));
            
            
            }
        } catch (Exception e) {
        }
    
    }
    
    public boolean issueBook(){
        
        boolean isIssued=false;
     
        int bookId= Integer.parseInt(txt_bookId.getText());
        int studentId= Integer.parseInt(txt_studentId.getText());
        String bookName = lbl_bookName.getText();
        String studentName = lbl_studentName.getText();
        String issuedate = txt_issuedate.getText();
        String duedate = txt_duedate.getText();
        
        try {
            Connection con = DBConnection.getConnection();
            String sql= "insert into issue_book_details(book_id,book_name,student_id,student_name,issue_date,due_date,status) values(?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1,bookId);
            pst.setString(2,bookName);
            pst.setInt(3,studentId);
            pst.setString(4,studentName);
            pst.setString(5,issuedate);
            pst.setString(6,duedate);
            pst.setString(7,"pending");
            
            
            int rowCount = pst.executeUpdate();
            if (rowCount > 0){
                isIssued = true;
              }
            else{
            isIssued=false;
            }
            
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isIssued;
    
    }
    
   public boolean isAlreadyIssued(){
    boolean isAlreadyIssued = false;
   int bookId= Integer.parseInt(txt_bookId.getText());
        int studentId= Integer.parseInt(txt_studentId.getText());
        try {
           Connection con = DBConnection.getConnection();
            String sql= "select * from issue_book_details where book_id=? and student_id=? and status =? ";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1,bookId);
            pst.setInt(2,studentId);
            pst.setString(3,"pending");
            
            ResultSet rs = pst.executeQuery();
            if (rs.next()){
                isAlreadyIssued = true;
              }
            else{
            isAlreadyIssued=false;
            }
       } catch (Exception e) {
           e.printStackTrace();
       }
   return isAlreadyIssued;
   
   }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        lbl_branch = new javax.swing.JLabel();
        lbl_studentId = new javax.swing.JLabel();
        lbl_studentName = new javax.swing.JLabel();
        lbl_course = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        xpanel = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        backpanel1 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        lbl_bookId = new javax.swing.JLabel();
        lbl_bookName = new javax.swing.JLabel();
        lbl_author = new javax.swing.JLabel();
        lbl_quantity = new javax.swing.JLabel();
        Id1 = new javax.swing.JLabel();
        Id2 = new javax.swing.JLabel();
        Id4 = new javax.swing.JLabel();
        b_add = new rojerusan.RSMaterialButtonCircle();
        txt_duedate = new app.bolivia.swing.JCTextField();
        txt_bookId = new app.bolivia.swing.JCTextField();
        txt_studentId = new app.bolivia.swing.JCTextField();
        txt_issuedate = new app.bolivia.swing.JCTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setBackground(new java.awt.Color(255, 255, 255));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Branch:");
        jPanel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, -1));

        jLabel59.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("Student Name:");
        jPanel5.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel60.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("Course:");
        jPanel5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 320, 5));

        jLabel61.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Student ID:");
        jPanel5.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel58.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 27)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Student_Registration_100px_2.png"))); // NOI18N
        jLabel58.setText("Student details");
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        lbl_branch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_branch.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(lbl_branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 610, 150, 40));

        lbl_studentId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_studentId.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(lbl_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 150, 40));

        lbl_studentName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_studentName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(lbl_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 150, 40));

        lbl_course.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_course.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(lbl_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 150, 40));

        panel_main.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 420, 800));

        jLabel57.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 27)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 0, 0));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Book_50px_1.png"))); // NOI18N
        jLabel57.setText("Issue Book");
        panel_main.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, -1, -1));

        jPanel41.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panel_main.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 220, 280, 10));

        xpanel.setBackground(new java.awt.Color(255, 51, 51));
        xpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xpanelMouseClicked(evt);
            }
        });

        x.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        x.setText("X");

        javax.swing.GroupLayout xpanelLayout = new javax.swing.GroupLayout(xpanel);
        xpanel.setLayout(xpanelLayout);
        xpanelLayout.setHorizontalGroup(
            xpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xpanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        xpanelLayout.setVerticalGroup(
            xpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        panel_main.add(xpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 80, 40));

        Id.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        Id.setForeground(new java.awt.Color(255, 51, 51));
        Id.setText("Enter Book ID:");
        panel_main.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 170, 80));

        jPanel39.setBackground(new java.awt.Color(153, 0, 0));
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backpanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel65.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel65.setText("Back");
        jLabel65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel65MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backpanel1Layout = new javax.swing.GroupLayout(backpanel1);
        backpanel1.setLayout(backpanel1Layout);
        backpanel1Layout.setHorizontalGroup(
            backpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel65)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        backpanel1Layout.setVerticalGroup(
            backpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backpanel1Layout.createSequentialGroup()
                .addComponent(jLabel65)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel39.add(backpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        jLabel66.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Quantity:");
        jPanel39.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, -1));

        jLabel67.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 27)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel67.setText("Book details");
        jPanel39.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel69.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Book Name:");
        jPanel39.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        jLabel70.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Author:");
        jPanel39.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel39.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 320, 5));

        jLabel71.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Book ID:");
        jPanel39.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        lbl_bookId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_bookId.setForeground(new java.awt.Color(255, 255, 255));
        jPanel39.add(lbl_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 150, 40));

        lbl_bookName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_bookName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel39.add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 150, 40));

        lbl_author.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_author.setForeground(new java.awt.Color(255, 255, 255));
        jPanel39.add(lbl_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 150, 40));

        lbl_quantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_quantity.setForeground(new java.awt.Color(255, 255, 255));
        jPanel39.add(lbl_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 150, 40));

        panel_main.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 800));

        Id1.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        Id1.setForeground(new java.awt.Color(255, 51, 51));
        Id1.setText("Enter Student ID:");
        panel_main.add(Id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, 170, 80));

        Id2.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        Id2.setForeground(new java.awt.Color(255, 51, 51));
        Id2.setText("Issue Date:");
        panel_main.add(Id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, 170, 80));

        Id4.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        Id4.setForeground(new java.awt.Color(255, 51, 51));
        Id4.setText("Issue Date:");
        panel_main.add(Id4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 170, 80));

        b_add.setBackground(new java.awt.Color(255, 51, 51));
        b_add.setText("Issue Book");
        b_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addActionPerformed(evt);
            }
        });
        panel_main.add(b_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 670, 270, 70));
        panel_main.add(txt_duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 570, -1, -1));

        txt_bookId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bookIdFocusLost(evt);
            }
        });
        panel_main.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 330, -1, -1));

        txt_studentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_studentIdFocusLost(evt);
            }
        });
        panel_main.add(txt_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 410, -1, -1));
        panel_main.add(txt_issuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, -1, -1));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel65MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel65MouseClicked

    private void xpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xpanelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_xpanelMouseClicked

    private void b_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addActionPerformed
        // TODO add your handling code here:
        
        if(lbl_quantity.getText().equals("0")){
        JOptionPane.showMessageDialog(this, "not available");
        }
        else{
        if (isAlreadyIssued()==false){
        if (issueBook()==true){
        JOptionPane.showMessageDialog(this, "book issued");
        }
        else{
        JOptionPane.showMessageDialog(this, "book not issued");
        }
        }else{
        JOptionPane.showMessageDialog(this, "already issued");
        }
        }
    }//GEN-LAST:event_b_addActionPerformed

    private void txt_bookIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bookIdFocusLost
        // TODO add your handling code here:
        
        if (!txt_bookId.getText().equals("")){
        getBookDetails();
        }
    }//GEN-LAST:event_txt_bookIdFocusLost

    private void txt_studentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_studentIdFocusLost
        // TODO add your handling code here:
                if (!txt_studentId.getText().equals("")){
        getStudentDetails();
        }
        
    }//GEN-LAST:event_txt_studentIdFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Id1;
    private javax.swing.JLabel Id2;
    private javax.swing.JLabel Id4;
    private rojerusan.RSMaterialButtonCircle b_add;
    private javax.swing.JPanel backpanel1;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_author;
    private javax.swing.JLabel lbl_bookId;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_branch;
    private javax.swing.JLabel lbl_course;
    private javax.swing.JLabel lbl_quantity;
    private javax.swing.JLabel lbl_studentId;
    private javax.swing.JLabel lbl_studentName;
    private javax.swing.JPanel panel_main;
    private app.bolivia.swing.JCTextField txt_bookId;
    private app.bolivia.swing.JCTextField txt_duedate;
    private app.bolivia.swing.JCTextField txt_issuedate;
    private app.bolivia.swing.JCTextField txt_studentId;
    private javax.swing.JLabel x;
    private javax.swing.JPanel xpanel;
    // End of variables declaration//GEN-END:variables
}
