/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author rumia
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    
    // validation
    
    public boolean validatelogin(){
        String name = txt_username.getText();
        String pwd = txt_password.getText();
        
        if (name.equals("")){
            JOptionPane.showMessageDialog(this,"please enter username ");
            return false;
        }
        if (pwd.equals("")){
           JOptionPane.showMessageDialog(this,"please enter password");
           return false;
                   
        }
           return true;
        }
        
    // validation creds
    public void login(){
        String name = txt_username.getText();
        String pwd = txt_password.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms", "root","");
            
         PreparedStatement pst = con.prepareStatement("select * from users where name = ? and password =?");
          pst.setString (1, name);
          pst.setString (2, pwd);
          
            ResultSet rs = pst.executeQuery();
            if (rs.next()){
            //JOptionPane.showMessageDialog(this,"login successful");
            ManageBooks mbook = new ManageBooks();
            mbook.setVisible(true);
            this.dispose();
            }
            else {
            JOptionPane.showMessageDialog(this,"incorrect");
            }

            
        } catch (Exception e) {
            e.printStackTrace();
        }

        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        welcome1 = new javax.swing.JLabel();
        welcome2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logint = new javax.swing.JLabel();
        logint1 = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        txt_password = new app.bolivia.swing.JCTextField();
        passi = new javax.swing.JLabel();
        txt_username = new app.bolivia.swing.JCTextField();
        b_signup = new rojerusan.RSMaterialButtonCircle();
        b_login = new rojerusan.RSMaterialButtonCircle();
        jPanel3 = new javax.swing.JPanel();
        X = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();
        useri = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Yu Gothic", 3, 20)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 102, 102));
        Title.setText("Boipoka");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        welcome1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        welcome1.setForeground(new java.awt.Color(102, 102, 255));
        welcome1.setText("Advance Library Application");
        jPanel1.add(welcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 270, 40));

        welcome2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        welcome2.setForeground(new java.awt.Color(255, 102, 102));
        welcome2.setText("Welcome To A");
        jPanel1.add(welcome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-3.png.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 780, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 830));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logint.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        logint.setForeground(new java.awt.Color(255, 255, 255));
        logint.setText("Login To Your Account");
        jPanel2.add(logint, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        logint1.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        logint1.setForeground(new java.awt.Color(255, 255, 255));
        logint1.setText("Login page");
        jPanel2.add(logint1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        pass.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("Password");
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 140, 30));

        txt_password.setBackground(new java.awt.Color(102, 102, 255));
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_password.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        txt_password.setPlaceholder("Enter Book ID");
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 250, -1));

        passi.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        passi.setForeground(new java.awt.Color(255, 255, 255));
        passi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secure_50px.png"))); // NOI18N
        jPanel2.add(passi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 60, 50));

        txt_username.setBackground(new java.awt.Color(102, 102, 255));
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_username.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        txt_username.setPlaceholder("Enter Book ID");
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 250, -1));

        b_signup.setBackground(new java.awt.Color(255, 102, 102));
        b_signup.setText("Signup");
        b_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_signupActionPerformed(evt);
            }
        });
        jPanel2.add(b_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 680, 330, 70));

        b_login.setBackground(new java.awt.Color(0, 0, 255));
        b_login.setText("Login");
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });
        jPanel2.add(b_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 600, 330, 70));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        X.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        X.setText("X");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(X)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(X)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 90, 50));

        user2.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        user2.setForeground(new java.awt.Color(255, 255, 255));
        user2.setText("Username");
        jPanel2.add(user2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 140, 30));

        useri.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        useri.setForeground(new java.awt.Color(255, 255, 255));
        useri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(useri, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 60, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 530, 830));

        setSize(new java.awt.Dimension(1539, 836));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_signupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_signupActionPerformed

    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        // TODO add your handling code here:
        if (validatelogin()) {
             login(); 
}
    }//GEN-LAST:event_b_loginActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel X;
    private rojerusan.RSMaterialButtonCircle b_login;
    private rojerusan.RSMaterialButtonCircle b_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logint;
    private javax.swing.JLabel logint1;
    private javax.swing.JLabel pass;
    private javax.swing.JLabel passi;
    private app.bolivia.swing.JCTextField txt_password;
    private app.bolivia.swing.JCTextField txt_username;
    private javax.swing.JLabel user2;
    private javax.swing.JLabel useri;
    private javax.swing.JLabel welcome1;
    private javax.swing.JLabel welcome2;
    // End of variables declaration//GEN-END:variables
}
