/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author rumia
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
    public ReturnBook() {
        initComponents();
    }
    
    //updating book count
public void updateBookCount () {
     int bookId =Integer.parseInt(txt_bookId.getText ());
      try { 
        Connection con = DBConnection.getConnection();
         String sql = "update book_details set quantity = quantity - 1 where book_id = ?";
         PreparedStatement pst= con.prepareStatement(sql);
        pst.setInt (1, bookId);
         int rowCount = pst.executeUpdate ();
         if (rowCount > 0)
                           {
             JOptionPane.showMessageDialog(this, "book count updated");
             int initialCount = Integer.parseInt (lbl_dueDate.getText ());
             lbl_dueDate.setText Integer.tostring(initialCount - 1));
         } else {
            JOptionPane.showMessageDialog(this, "can't update book count");
         
     } catch (Exception e) {
        e.printStackTrace();
     
     }  
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        xpanel = new javax.swing.JPanel();
        x = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        txt_bookId = new app.bolivia.swing.JCTextField();
        jPanel39 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        lbl_issueDate = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        lbl_bookId = new javax.swing.JLabel();
        lbl_bookName = new javax.swing.JLabel();
        lbl_studentName = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        lbl_bookError = new javax.swing.JLabel();
        lbl_dueDate1 = new javax.swing.JLabel();
        lbl_dueDate2 = new javax.swing.JLabel();
        Id1 = new javax.swing.JLabel();
        txt_studentId = new app.bolivia.swing.JCTextField();
        b_add = new rojerusan.RSMaterialButtonCircle();
        backpanel1 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        b_add1 = new rojerusan.RSMaterialButtonCircle();
        jLabel72 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setBackground(new java.awt.Color(255, 255, 255));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel57.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 27)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 0, 0));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Book_50px_1.png"))); // NOI18N
        jLabel57.setText("Return Book");
        panel_main.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 180, -1, -1));

        jPanel41.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panel_main.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 240, 280, 10));

        xpanel.setBackground(new java.awt.Color(255, 51, 51));
        xpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xpanelMouseClicked(evt);
            }
        });

        x.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        x.setText("X");

        javax.swing.GroupLayout xpanelLayout = new javax.swing.GroupLayout(xpanel);
        xpanel.setLayout(xpanelLayout);
        xpanelLayout.setHorizontalGroup(
            xpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xpanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        xpanelLayout.setVerticalGroup(
            xpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(x)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        panel_main.add(xpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1590, 10, 80, 40));

        Id.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        Id.setForeground(new java.awt.Color(255, 51, 51));
        Id.setText("Enter Book ID:");
        panel_main.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 330, 170, 80));

        txt_bookId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 51)));
        txt_bookId.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        txt_bookId.setPlaceholder("Enter Book ID");
        txt_bookId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bookIdActionPerformed(evt);
            }
        });
        panel_main.add(txt_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 350, 250, -1));

        jPanel39.setBackground(new java.awt.Color(255, 0, 51));
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Issued date:");
        jPanel39.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 130, -1));

        jLabel67.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 27)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel67.setText("Book details");
        jPanel39.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        lbl_issueDate.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        lbl_issueDate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel39.add(lbl_issueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 170, 50));

        jLabel69.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Book Name:");
        jPanel39.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel70.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Student Name:");
        jPanel39.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 140, -1));

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel39.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 320, 5));

        jLabel71.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Issue ID:");
        jPanel39.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 90, -1));

        lbl_bookId.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        lbl_bookId.setForeground(new java.awt.Color(255, 255, 255));
        jPanel39.add(lbl_bookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 170, 50));

        lbl_bookName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        lbl_bookName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel39.add(lbl_bookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 170, 50));

        lbl_studentName.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        lbl_studentName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel39.add(lbl_studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 170, 50));

        jLabel68.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Due Date:");
        jPanel39.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 130, -1));

        lbl_bookError.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        lbl_bookError.setForeground(new java.awt.Color(255, 255, 255));
        jPanel39.add(lbl_bookError, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 700, 370, 50));

        lbl_dueDate1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        lbl_dueDate1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel39.add(lbl_dueDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, 170, 50));

        lbl_dueDate2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        lbl_dueDate2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel39.add(lbl_dueDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, 170, 50));

        panel_main.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 450, 800));

        Id1.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        Id1.setForeground(new java.awt.Color(255, 51, 51));
        Id1.setText("Enter Student ID:");
        panel_main.add(Id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 400, 170, 80));

        txt_studentId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 0, 51)));
        txt_studentId.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        txt_studentId.setPlaceholder("Enter Student ID");
        panel_main.add(txt_studentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 420, 250, -1));

        b_add.setBackground(new java.awt.Color(102, 102, 255));
        b_add.setText("Return Book");
        b_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_addActionPerformed(evt);
            }
        });
        panel_main.add(b_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 650, 270, 70));

        backpanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel65.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel65.setText("Back");
        jLabel65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel65MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backpanel1Layout = new javax.swing.GroupLayout(backpanel1);
        backpanel1.setLayout(backpanel1Layout);
        backpanel1Layout.setHorizontalGroup(
            backpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel65)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        backpanel1Layout.setVerticalGroup(
            backpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backpanel1Layout.createSequentialGroup()
                .addComponent(jLabel65)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_main.add(backpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        b_add1.setBackground(new java.awt.Color(51, 102, 255));
        b_add1.setText("Find");
        b_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_add1ActionPerformed(evt);
            }
        });
        panel_main.add(b_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 540, 270, 70));

        jLabel72.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-2.png"))); // NOI18N
        jLabel72.setText("Issue ID:");
        panel_main.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 760));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, -10, 1670, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel65MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel65MouseClicked

    private void xpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xpanelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_xpanelMouseClicked

    private void txt_bookIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bookIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bookIdActionPerformed

    private void b_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_addActionPerformed

    private void b_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_add1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_add1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Id1;
    private rojerusan.RSMaterialButtonCircle b_add;
    private rojerusan.RSMaterialButtonCircle b_add1;
    private javax.swing.JPanel backpanel1;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JLabel lbl_bookError;
    private javax.swing.JLabel lbl_bookId;
    private javax.swing.JLabel lbl_bookName;
    private javax.swing.JLabel lbl_dueDate1;
    private javax.swing.JLabel lbl_dueDate2;
    private javax.swing.JLabel lbl_issueDate;
    private javax.swing.JLabel lbl_studentName;
    private javax.swing.JPanel panel_main;
    private app.bolivia.swing.JCTextField txt_bookId;
    private app.bolivia.swing.JCTextField txt_studentId;
    private javax.swing.JLabel x;
    private javax.swing.JPanel xpanel;
    // End of variables declaration//GEN-END:variables
}
